// Estilo: Caderno de Campo Editorial. Esta página transforma cada item em uma leitura de evidências, com tipografia Fraunces + IBM Plex Sans.
import "@/editorial.css";
import { useMemo, useRef, useState } from "react";
import { ArrowRight, Check, ChevronDown, ClipboardCheck, Film, FlaskConical, GitBranch, Leaf, LockKeyhole, Map, Play, RotateCcw, Send, Sparkles, Table2, Timer, TriangleAlert } from "lucide-react";
import { roster, type Student } from "@/data-roster";
import { submitAssessment } from "@/lib/submission";

const ASSET_BASE = `${import.meta.env.BASE_URL}assets/`;
const VIDEO_URL = `${ASSET_BASE}teorias-evolucionistas-9ano.mp4`;
const REFERENCE_IMAGE = `${ASSET_BASE}evo-campo-reference.png`;
const ADAPTATION_IMAGE = `${ASSET_BASE}evo-campo-reference.png`;
const MARK_IMAGE = `${ASSET_BASE}evo-campo-mark.svg`;
const HOMOLOGY_IMAGE = `${ASSET_BASE}homology-vertebrates.png`;
const WHALE_SKELETON_IMAGE = `${ASSET_BASE}whale-skeleton.png`;
const PEPPERED_MOTH_IMAGE = `${ASSET_BASE}peppered-moth.jpg`;
const TIKTAALIK_IMAGE = `${ASSET_BASE}tiktaalik.jpg`;
const FINCHES_IMAGE = `${ASSET_BASE}darwins-finches.jpeg`;

const answerKey: Record<string, string> = { q1: "B", q2: "C", q3: "A", q4: "D", q5: "C", q6: "B", q7: "D", q8: "A", q9: "C", q10: "B", q11: "A", q12: "D" };

type EvidenceType = "video" | "simulator" | "chart" | "cladogram" | "table" | "clade" | "timeline" | "fossil" | "genetics" | "concept" | "islands" | "diversity";
type Question = { id: string; lesson: number; eyebrow: string; title: string; prompt: string; evidence: EvidenceType; options: { letter: string; text: string }[]; rationale: string };

const lessons = [
  { number: "01", title: "Isolamento", short: "Especiação e adaptação", icon: GitBranch },
  { number: "02", title: "Linhagens", short: "Cladogramas e convergência", icon: GitBranch },
  { number: "03", title: "Vestígios", short: "Fósseis e genética", icon: FlaskConical },
  { number: "04", title: "Diversidade", short: "Evolução e biodiversidade", icon: Leaf },
];

const questions: Question[] = [
  { id: "q1", lesson: 0, eyebrow: "Pista 01 · vídeo", title: "Duas explicações para o mesmo exemplo", prompt: "Uma turma compara o exemplo das girafas apresentado no vídeo. Na primeira explicação, o esforço para alcançar folhas altas faria o pescoço crescer durante a vida e essa mudança seria passada aos descendentes. Na segunda, uma população já apresentava variações; em períodos de escassez, as girafas que alcançavam melhor o alimento deixavam mais descendentes. Qual interpretação está mais de acordo com a seleção natural e com a síntese evolutiva atual?", evidence: "video", options: [{ letter: "A", text: "A primeira explicação, porque qualquer mudança no corpo de um indivíduo altera imediatamente os seus genes reprodutivos." }, { letter: "B", text: "A segunda explicação, porque a seleção atua sobre variações herdáveis e modifica a frequência de características na população ao longo das gerações." }, { letter: "C", text: "As duas explicações são equivalentes, pois toda adaptação ocorre por esforço intencional do organismo." }, { letter: "D", text: "Nenhuma das duas, porque o ambiente não influencia a sobrevivência nem a reprodução." }], rationale: "A seleção natural atua sobre variações herdáveis e altera frequências na população. Um caráter adquirido durante a vida não é automaticamente inscrito nos genes reprodutivos." },
  { id: "q2", lesson: 0, eyebrow: "Pista 02 · simulador", title: "Quando uma população deixa de trocar genes", prompt: "No simulador, uma população de lagartos vive numa área contínua. Depois de uma mudança no rio, parte da população passa a viver numa ilha. Nas primeiras gerações, ainda há diferenças de cor entre os lagartos, mas não ocorre cruzamento entre ilha e continente. Qual conjunto de observações forneceria a melhor evidência de que o isolamento pode contribuir para a especiação?", evidence: "simulator", options: [{ letter: "A", text: "Os lagartos ficam maiores, porque o tamanho é sempre uma resposta direta à necessidade." }, { letter: "B", text: "Todos os lagartos passam a ter exatamente a mesma cor, pois a evolução elimina toda a variação." }, { letter: "C", text: "Após muitas gerações, as populações acumulam diferenças e deixam de produzir descendentes férteis quando reunidas." }, { letter: "D", text: "A ilha desaparece, porque o isolamento geográfico impede qualquer mudança biológica." }], rationale: "O isolamento geográfico pode reduzir o fluxo gênico. Se diferenças se acumularem e houver isolamento reprodutivo, a formação de novas espécies torna-se uma hipótese sustentada." },
  { id: "q3", lesson: 0, eyebrow: "Pista 03 · gráfico", title: "A frequência muda, a população responde", prompt: "O gráfico didático mostra a proporção de bicos finos e largos numa população de aves. Na estação de sementes macias, os bicos finos aumentam de 52% para 68%. Na estação seguinte, com sementes duras predominantes, os bicos largos aumentam de 31% para 57%. Qual conclusão é mais consistente com os dados?", evidence: "chart", options: [{ letter: "A", text: "O ambiente pode alterar o sucesso de sobrevivência e reprodução de variantes já presentes, fazendo a frequência relativa mudar entre gerações." }, { letter: "B", text: "Cada ave escolhe desenvolver o bico mais adequado e transmite essa escolha aos seus filhotes." }, { letter: "C", text: "A população evolui porque os indivíduos mais fortes decidem produzir uma nova característica." }, { letter: "D", text: "O gráfico prova que uma única estação transforma todos os bicos de uma ave durante a vida." }], rationale: "A leitura correta é populacional: o ambiente altera o sucesso reprodutivo relativo de variantes que já existem." },
  { id: "q4", lesson: 1, eyebrow: "Pista 04 · cladograma", title: "O nó que aproxima duas linhagens", prompt: "No cladograma da atividade, a linhagem X se separa primeiro; depois, a linhagem Y se separa de um ramo que contém Z e W. O nó que une Z e W está mais próximo deles do que o nó que os une a Y. Qual afirmação é sustentada pelo cladograma?", evidence: "cladogram", options: [{ letter: "A", text: "X é ancestral direto de todas as outras linhagens." }, { letter: "B", text: "Y e X são necessariamente iguais em todas as características." }, { letter: "C", text: "W surgiu a partir de Z na geração imediatamente anterior." }, { letter: "D", text: "Z e W compartilham um ancestral comum mais recente entre si do que com Y." }], rationale: "O cladograma expressa ancestralidade comum relativa. Ele não mostra uma fila de transformações diretas nem permite chamar uma espécie atual de ancestral de outra." },
  { id: "q5", lesson: 1, eyebrow: "Pista 05 · tabela", title: "Semelhança de função não é sempre parentesco", prompt: "Uma tabela compara duas situações: (I) asas de insetos e asas de aves, com funções semelhantes e origens evolutivas diferentes; (II) braço humano, asa de morcego e nadadeira de baleia, com o mesmo plano estrutural de membro anterior, mas funções diferentes. Como interpretar as situações?", evidence: "table", options: [{ letter: "A", text: "I é divergente porque todas as asas têm a mesma origem; II é convergente porque as funções são diferentes." }, { letter: "B", text: "I e II são exemplos de seleção artificial, pois foram produzidos por ação humana." }, { letter: "C", text: "I ilustra evolução convergente; II ilustra evolução divergente a partir de uma estrutura ancestral comum." }, { letter: "D", text: "I e II mostram que estruturas com funções parecidas sempre têm o mesmo ancestral recente." }], rationale: "A origem e a função precisam ser analisadas juntas: funções semelhantes podem surgir separadamente, enquanto uma estrutura ancestral pode divergir para funções diferentes." },
  { id: "q6", lesson: 1, eyebrow: "Pista 06 · grupo", title: "O que torna um grupo monofilético?", prompt: "No painel de cladograma, quatro cartões podem ser selecionados como grupo. Um grupo é considerado monofilético quando reúne um ancestral comum e todos os seus descendentes. Qual seleção representa um grupo monofilético no diagrama da atividade?", evidence: "clade", options: [{ letter: "A", text: "O ancestral do ramo e apenas duas das quatro linhagens que descendem dele." }, { letter: "B", text: "O nó indicado e todas as linhagens que saem desse nó até às extremidades." }, { letter: "C", text: "Quaisquer duas espécies que tenham aparência semelhante, mesmo em ramos separados." }, { letter: "D", text: "A linhagem mais antiga isolada, sem incluir o ancestral comum indicado." }], rationale: "O critério é estrutural: um grupo monofilético inclui o ancestral comum e todas as linhagens descendentes desse nó." },
  { id: "q7", lesson: 2, eyebrow: "Pista 07 · linha do tempo", title: "Uma explicação que se amplia com evidências", prompt: "A linha do tempo apresenta, entre outros marcos, Lamarck (1809), Darwin e Wallace (1858–1859), Mendel (1866) e a síntese evolutiva moderna (século XX). O que a sequência revela sobre a construção do conhecimento científico?", evidence: "timeline", options: [{ letter: "A", text: "A primeira hipótese formulada torna todas as explicações posteriores desnecessárias." }, { letter: "B", text: "A genética de Mendel foi criada depois da síntese moderna para confirmar uma teoria já completa." }, { letter: "C", text: "As ideias científicas não mudam; apenas recebem datas diferentes em livros diferentes." }, { letter: "D", text: "Novas evidências e conceitos podem ampliar, corrigir ou integrar explicações anteriores, como ocorreu com a genética e a seleção natural." }], rationale: "A ciência é uma construção histórica: ideias são revistas, testadas e integradas quando novas evidências e conceitos tornam a explicação mais completa." },
  { id: "q8", lesson: 2, eyebrow: "Pista 08 · fóssil", title: "O que os vestígios permitem inferir?", prompt: "O infográfico mostra fósseis de membros anteriores com ossos correspondentes em diferentes mamíferos, além de mudanças graduais na forma desses ossos ao longo de camadas geológicas. Qual argumento é mais bem apoiado por esse conjunto de evidências?", evidence: "fossil", options: [{ letter: "A", text: "Estruturas homólogas e fósseis podem sustentar a hipótese de ancestralidade comum e de mudanças acumuladas ao longo do tempo." }, { letter: "B", text: "A semelhança prova que todas as espécies viveram exatamente no mesmo local e na mesma época." }, { letter: "C", text: "O fóssil permite observar diretamente cada geração, sem necessidade de inferência." }, { letter: "D", text: "A existência de fósseis elimina a necessidade de comparar anatomia ou material genético." }], rationale: "Fósseis e anatomia comparada são evidências complementares. A ancestralidade comum é uma inferência apoiada por padrões, não uma observação direta de cada geração." },
  { id: "q9", lesson: 2, eyebrow: "Pista 09 · dados genéticos", title: "Semelhança genética: uma pista, não uma sentença", prompt: "A tabela é um modelo didático hipotético de semelhanças em regiões de DNA entre uma linhagem de referência e três espécies. Os valores são: espécie A — 91%; espécie B — 97%; espécie C — 84%. Qual inferência é mais adequada, considerando somente este conjunto de dados?", evidence: "genetics", options: [{ letter: "A", text: "A espécie A é necessariamente ancestral direta da espécie de referência." }, { letter: "B", text: "A espécie C não possui qualquer relação evolutiva com a espécie de referência." }, { letter: "C", text: "A espécie B apresenta maior semelhança nessa região analisada e pode ser investigada como parente evolutivo mais próximo entre as três, sem concluir sozinha toda a história evolutiva." }, { letter: "D", text: "A espécie B é a mais antiga porque apresenta a maior percentagem de semelhança." }], rationale: "O dado permite uma inferência comparativa limitada. Maior semelhança não significa ancestralidade direta nem resume toda a história evolutiva." },
  { id: "q10", lesson: 3, eyebrow: "Pista 10 · mapa conceitual", title: "Ligar os processos sem atribuir intenção", prompt: "No mapa conceitual, cinco cartões devem ser ligados: variação herdável, pressão ambiental, sucesso reprodutivo diferencial, mudança na frequência de características e biodiversidade. Qual sequência expressa melhor a relação entre os processos?", evidence: "concept", options: [{ letter: "A", text: "Pressão ambiental → cria variação herdável → todos os indivíduos mudam → biodiversidade desaparece." }, { letter: "B", text: "Variação herdável + pressão ambiental → diferenças no sucesso reprodutivo → mudança de frequências ao longo das gerações → divergência e biodiversidade." }, { letter: "C", text: "Biodiversidade → impede qualquer seleção → variação herdável → indivíduos escolhem as características." }, { letter: "D", text: "Sucesso reprodutivo diferencial → transforma diretamente um indivíduo → pressão ambiental → uma única espécie para sempre." }], rationale: "A evolução é explicada na relação entre variação, ambiente, reprodução e gerações; não como decisão consciente nem transformação instantânea do indivíduo." },
  { id: "q11", lesson: 3, eyebrow: "Pista 11 · mapa", title: "Três áreas, três histórias evolutivas", prompt: "No mapa didático, uma população de sapos ocupava uma bacia contínua. Uma estrada e um período de seca dividiram o ambiente em três áreas. Os grupos passaram a vocalizar em horários diferentes e, quando reunidos, cruzam com dificuldade. Qual interpretação articula melhor o mapa e a situação descrita?", evidence: "islands", options: [{ letter: "A", text: "O isolamento geográfico pode reduzir o fluxo gênico e, junto com diferenças acumuladas e isolamento reprodutivo, favorecer a especiação." }, { letter: "B", text: "A estrada determina geneticamente uma nova espécie no mesmo dia em que é construída." }, { letter: "C", text: "A mudança de vocalização prova que os sapos decidiram adaptar-se para formar novas espécies." }, { letter: "D", text: "O isolamento impede evolução, pois nenhuma população isolada pode apresentar variação." }], rationale: "A especiação é gradual: o isolamento reduz o fluxo gênico e pode ser acompanhado por diferenças acumuladas e isolamento reprodutivo." },
  { id: "q12", lesson: 3, eyebrow: "Pista 12 · síntese", title: "Evolução como fonte de diversidade", prompt: "O gráfico final compara quatro linhagens hipotéticas ao longo de muitas gerações. As linhagens que ocupam ambientes distintos acumulam diferenças e passam a utilizar recursos diferentes; o número de formas e nichos ocupados aumenta. Qual conclusão relaciona melhor evolução e biodiversidade?", evidence: "diversity", options: [{ letter: "A", text: "Biodiversidade é apenas a quantidade de indivíduos, sem relação com diferenças entre linhagens." }, { letter: "B", text: "Se uma linhagem se adapta, todas as outras precisam adquirir exatamente a mesma característica." }, { letter: "C", text: "A evolução reduz sempre a biodiversidade porque favorece apenas o indivíduo mais forte." }, { letter: "D", text: "Divergência entre populações, associada a diferentes ambientes e isolamento, pode originar linhagens com características e modos de vida distintos, contribuindo para a biodiversidade." }], rationale: "A divergência entre populações, em ambientes e trajetórias diferentes, pode gerar novas formas, nichos e linhagens, aumentando a biodiversidade." },
];

function EvidenceBlock({ type, isolated, setIsolated }: { type: EvidenceType; isolated: boolean; setIsolated: (value: boolean) => void }) {
  if (type === "video") return <div className="evidence evidence-video"><div className="evidence-kicker"><Film size={15} /> trecho para observar</div><div className="evidence-quote">“A adaptação deixa de ser uma intenção individual e passa a ser uma história de população.”</div><div className="evidence-note">Volta ao minuto em que o vídeo compara Lamarck e Darwin.</div></div>;
  if (type === "simulator") return <div className="evidence evidence-simulator"><div className="evidence-kicker"><Timer size={15} /> simulador de fluxo gênico</div><div className="simulator-real-evidence"><figure className="real-figure real-figure-small"><img src={PEPPERED_MOTH_IMAGE} alt="Larva real de uma mariposa da família Geometridae fotografada sobre vegetação" /><figcaption><strong>Geometridae · fase larvar</strong><span>fotografia real · camuflagem como pista</span></figcaption></figure><div><p className="real-evidence-copy">A fotografia mostra um organismo real em contexto de camuflagem. Usa os botões para comparar uma população com troca de genes e outra com fluxo reduzido.</p><div className="simulator-toggle"><button className={!isolated ? "active" : ""} aria-pressed={!isolated} onClick={() => setIsolated(false)} type="button">Sem barreira</button><button className={isolated ? "active" : ""} aria-pressed={isolated} onClick={() => setIsolated(true)} type="button">Barreira ativa</button></div><div className="population-track"><div className="population-group"><span className="population-dot dot-a" /><span className="population-dot dot-b" /><span className="population-dot dot-c" /></div><div className={`barrier ${isolated ? "is-on" : ""}`}><span>{isolated ? "fluxo reduzido" : "troca de genes"}</span></div><div className="population-group right"><span className="population-dot dot-c" /><span className="population-dot dot-a" /><span className="population-dot dot-b" /></div></div><p className="simulator-caption">{isolated ? "As duas populações passam a acumular diferenças com pouca troca de genes." : "As populações permanecem conectadas e o fluxo gênico reduz a divergência."}</p></div></div></div>;
  if (type === "chart") return <div className="evidence evidence-chart"><div className="evidence-kicker"><FlaskConical size={15} /> gráfico-modelo · frequência relativa</div><svg viewBox="0 0 560 184" role="img" aria-label="Gráfico comparando bicos finos e largos em duas estações"><line x1="44" y1="148" x2="534" y2="148" className="axis" /><line x1="44" y1="24" x2="44" y2="148" className="axis" /><line x1="44" y1="86" x2="534" y2="86" className="grid-line" /><text x="10" y="28">100%</text><text x="18" y="91">50%</text><text x="27" y="152">0%</text><rect x="92" y="84" width="42" height="64" rx="8" className="bar-teal" /><rect x="142" y="100" width="42" height="48" rx="8" className="bar-ochre" /><rect x="264" y="64" width="42" height="84" rx="8" className="bar-teal" /><rect x="314" y="77" width="42" height="71" rx="8" className="bar-ochre" /><text x="95" y="171">macias</text><text x="266" y="171">duras</text><text x="93" y="78">52%</text><text x="265" y="58">68%</text><text x="143" y="94">31%</text><text x="315" y="71">57%</text></svg><div className="chart-legend"><span><i className="legend-dot teal" /> bicos finos</span><span><i className="legend-dot ochre" /> bicos largos</span></div></div>;
  if (type === "cladogram") return <div className="evidence evidence-cladogram"><div className="evidence-kicker"><GitBranch size={15} /> leitura de parentesco relativo</div><div className="real-cladogram"><figure className="real-figure real-figure-finches"><img src={FINCHES_IMAGE} alt="Ilustração histórica de quatro tentilhões de Galápagos com formas de bico diferentes" /><figcaption><strong>Tentilhões de Darwin</strong><span>John Gould · 1845 · domínio público</span></figcaption></figure><div className="cladogram-reading"><svg viewBox="0 0 540 190" role="img" aria-label="Cladograma didático com quatro linhagens de tentilhões identificadas por X, Y, Z e W"><path d="M52 112H142M142 112V48M142 48H220M142 112V154M142 154H220M220 48V24M220 24H408M220 48V95M220 95H300M300 95V72M300 72H408M300 95V128M300 128H408M220 154H408" className="tree-line" /><circle cx="142" cy="112" r="6" className="tree-node" /><circle cx="220" cy="48" r="6" className="tree-node" /><circle cx="300" cy="95" r="6" className="tree-node" /><text x="28" y="116">X</text><text x="420" y="28">Y</text><text x="420" y="76">Z</text><text x="420" y="132">W</text><text x="104" y="34" className="small-svg-label">ancestralidade comum relativa</text></svg><p className="real-evidence-copy">A fotografia histórica mostra variação real de bicos; o cladograma ao lado organiza uma hipótese de parentesco, não uma sequência de “melhorias”.</p></div></div></div>;
  if (type === "table") return <div className="evidence evidence-table"><div className="evidence-kicker"><Table2 size={15} /> tabela de comparação · evidências reais</div><div className="real-evidence-strip"><figure className="real-figure"><img src={HOMOLOGY_IMAGE} alt="Comparação dos ossos dos membros anteriores de humano, cão, ave e baleia" /><figcaption><strong>Homologia</strong><span>Volkov · CC BY-SA 4.0</span></figcaption></figure><figure className="real-figure"><img src={WHALE_SKELETON_IMAGE} alt="Esqueleto de baleia com regiões do corpo indicadas" /><figcaption><strong>Esqueleto de baleia</strong><span>Meyers Konversationslexikon · domínio público</span></figcaption></figure></div><table><thead><tr><th>estrutura</th><th>função</th><th>origem</th></tr></thead><tbody><tr><td>asas de insetos + aves</td><td>voo</td><td>diferente</td></tr><tr><td>membro anterior de mamíferos</td><td>voo, nado, preensão</td><td>ancestral comum</td></tr></tbody></table><p className="source-credit">As fotografias e ilustrações são evidências; a conclusão exige comparar origem, função e contexto.</p></div>;
  if (type === "clade") return <div className="evidence evidence-clade"><div className="evidence-kicker"><GitBranch size={15} /> recorte monofilético</div><div className="clade-branch"><span className="clade-root" /><span className="clade-stem" /><span className="clade-leaf leaf-1">A</span><span className="clade-leaf leaf-2">B</span><span className="clade-leaf leaf-3">C</span><span className="clade-leaf leaf-4">D</span><span className="clade-bracket">grupo completo</span></div></div>;
  if (type === "timeline") return <div className="evidence evidence-timeline"><div className="evidence-kicker"><Timer size={15} /> linha do tempo · ideias e evidências</div><div className="timeline-row"><span><b>1809</b><em>Lamarck</em></span><span><b>1858–59</b><em>Darwin + Wallace</em></span><span><b>1866</b><em>Mendel</em></span><span><b>séc. XX</b><em>síntese</em></span></div></div>;
  if (type === "fossil") return <div className="evidence evidence-image"><figure className="real-figure real-figure-fossil"><img src={TIKTAALIK_IMAGE} alt="Fotografia de um molde de Tiktaalik roseae, fóssil de transição entre peixe e tetrápode" /><figcaption><strong>Tiktaalik roseae</strong><span>James St. John · CC BY 2.0 · molde exposto no Field Museum</span></figcaption></figure><div><div className="evidence-kicker"><Sparkles size={15} /> inferência a partir de vestígios</div><p>Um fóssil de transição combina características que ajudam a testar hipóteses sobre a passagem entre ambientes aquáticos e terrestres. Não é uma “metade” de cada animal nem uma prova isolada de toda a história.</p></div></div>;
  if (type === "genetics") return <div className="evidence evidence-table"><div className="evidence-kicker"><FlaskConical size={15} /> modelo didático hipotético · DNA</div><table><thead><tr><th>comparação</th><th>semelhança</th><th>leitura inicial</th></tr></thead><tbody><tr><td>espécie A</td><td>91%</td><td>menor</td></tr><tr className="highlight-row"><td>espécie B</td><td>97%</td><td>maior</td></tr><tr><td>espécie C</td><td>84%</td><td>menor</td></tr></tbody></table></div>;
  if (type === "concept") return <div className="evidence evidence-concept"><div className="evidence-kicker"><GitBranch size={15} /> mapa conceitual · arranjo lógico</div><div className="concept-map"><span className="concept-node node-1">variação herdável</span><span className="concept-arrow a-1">+</span><span className="concept-node node-2">pressão ambiental</span><span className="concept-arrow a-2">→</span><span className="concept-node node-3">sucesso reprodutivo</span><span className="concept-arrow a-3">→</span><span className="concept-node node-4">frequências mudam</span><span className="concept-arrow a-4">→</span><span className="concept-node node-5">biodiversidade</span></div></div>;
  if (type === "islands") return <div className="evidence evidence-islands"><div className="evidence-kicker"><Map size={15} /> mapa-modelo · fluxo gênico</div><svg viewBox="0 0 560 170" role="img" aria-label="Mapa com três áreas isoladas e populações de sapos"><path d="M0 80C70 33 132 52 188 77S315 110 370 71 472 21 560 58V170H0Z" className="map-water" /><path d="M74 64l74-15 41 36-36 50-80-18zM253 40l88 24-15 76-81-25zM416 77l74-21 46 47-47 39-71-26z" className="map-island" /><circle cx="129" cy="96" r="8" className="frog-dot" /><circle cx="296" cy="90" r="8" className="frog-dot" /><circle cx="455" cy="102" r="8" className="frog-dot" /><path d="M181 83L247 77M341 84L413 92" className="map-dashed" /></svg></div>;
  return <div className="evidence evidence-diversity"><div className="evidence-kicker"><Leaf size={15} /> gráfico-modelo · linhagens e nichos</div><svg viewBox="0 0 560 165" role="img" aria-label="Gráfico de aumento de formas e nichos ao longo das gerações"><line x1="46" y1="132" x2="534" y2="132" className="axis" /><line x1="46" y1="28" x2="46" y2="132" className="axis" /><path d="M52 126C145 126 174 111 222 108S289 85 334 80 418 54 524 31" className="chart-line" /><path d="M52 126C145 126 174 111 222 108S289 85 334 80 418 54 524 31L524 132H52Z" className="chart-area" /><text x="53" y="151">poucas gerações</text><text x="426" y="151">muitas gerações</text><text x="60" y="40">mais formas e nichos</text></svg></div>;
}

function Field({ label, value, wide = false, editable = false, onChange }: { label: string; value: string; wide?: boolean; editable?: boolean; onChange?: (value: string) => void }) {
  return <label className={`field ${wide ? "wide" : ""}`}><span>{label}</span><input value={value} readOnly={!editable} aria-readonly={!editable} onChange={(event) => onChange?.(event.target.value)} placeholder={editable ? "preencha" : "preenchido ao selecionar"} /></label>;
}

function QuestionCard({ question, value, onChange, submitted, isolated, setIsolated }: { question: Question; value: string | undefined; onChange: (id: string, value: string) => void; submitted: boolean; isolated: boolean; setIsolated: (value: boolean) => void }) {
  const isCorrect = submitted && value === answerKey[question.id];
  const isWrong = submitted && !isCorrect;
  return <article className={`question-card ${submitted ? (isCorrect ? "is-correct" : "is-wrong") : ""}`} id={question.id}>
    <div className="question-top"><span className="question-number">{question.id.replace("q", "Q")}</span><span className="question-eyebrow">{question.eyebrow}</span>{submitted && <span className={`answer-stamp ${isCorrect ? "stamp-correct" : "stamp-wrong"}`}>{isCorrect ? <><Check size={14} /> evidência consistente</> : <><TriangleAlert size={14} /> rever hipótese</>}</span>}</div>
    <h3>{question.title}</h3>
    <p className="question-prompt">{question.prompt}</p>
    <EvidenceBlock type={question.evidence} isolated={isolated} setIsolated={setIsolated} />
    <div className="options" role="radiogroup" aria-label={`Resposta da ${question.id}`}>
      {question.options.map((option) => <label key={option.letter} className={`option ${value === option.letter ? "selected" : ""} ${submitted && option.letter === answerKey[question.id] ? "correct-option" : ""}`}><input type="radio" name={question.id} value={option.letter} checked={value === option.letter} onChange={() => onChange(question.id, option.letter)} disabled={submitted} /><span className="option-letter">{option.letter}</span><span>{option.text}</span></label>)}
    </div>
    {submitted && <div className={`rationale ${isCorrect ? "rationale-correct" : "rationale-wrong"}`}><strong>{isCorrect ? "Leitura confirmada." : `A resposta de referência é ${answerKey[question.id]}.`}</strong><span>{question.rationale}</span></div>}
  </article>;
}

export default function Home() {
  const [selectedName, setSelectedName] = useState("");
  const [manualStudent, setManualStudent] = useState<Student>({ nome: "", numero: "", serie: "9.º Ano A", ra: "", digito: "", email: "", situacao: "identificação manual" });
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [saveState, setSaveState] = useState<{ type: "idle" | "saving" | "saved" | "local"; message?: string }>({ type: "idle" });
  const [watchedVideo, setWatchedVideo] = useState(false);
  const [isolated, setIsolated] = useState(true);
  const videoRef = useRef<HTMLVideoElement>(null);
  const selectedStudent = useMemo<Student | undefined>(() => roster.length > 0 ? roster.find((item) => item.nome === selectedName) : (manualStudent.nome.trim() ? manualStudent : undefined), [selectedName, manualStudent]);
  const answeredCount = Object.keys(answers).length;
  const score = questions.reduce((total, question) => total + (answers[question.id] === answerKey[question.id] ? 1 : 0), 0);
  const completion = Math.round((answeredCount / questions.length) * 100);

  const selectAnswer = (id: string, value: string) => setAnswers((current) => ({ ...current, [id]: value }));
  const updateManualStudent = (field: keyof Student, value: string) => setManualStudent((current) => ({ ...current, [field]: value }));
  const scrollToQuestions = () => document.getElementById("questions")?.scrollIntoView({ behavior: "smooth", block: "start" });
  const submit = async () => {
    if (!selectedStudent || answeredCount !== questions.length) {
      document.getElementById(!selectedStudent ? "student-record" : "questions")?.scrollIntoView({ behavior: "smooth", block: "start" });
      setSaveState({ type: "idle", message: !selectedStudent ? "Seleciona o teu nome para continuar." : "Responde às 12 questões antes de enviar." });
      return;
    }
    setSubmitted(true);
    setSaveState({ type: "saving", message: "A preparar o registo…" });
    const result = await submitAssessment({ submittedAt: new Date().toISOString(), student: selectedStudent, answers, score, total: questions.length });
    setSaveState({ type: result.mode === "online" ? "saved" : "local", message: result.message });
    window.setTimeout(() => document.getElementById("result")?.scrollIntoView({ behavior: "smooth", block: "start" }), 80);
  };

  return <div className="app-shell">
    <header className="topbar"><div className="school-lockup"><span className="school-kicker">E.E. POFª</span><span className="school-name">WANDA MASCAGNI DE SÁ</span></div><div className="brand-lockup"><img src={MARK_IMAGE} alt="" /><span>EVO <i>/</i> CAMPO</span></div><a className="teacher-link" href="#orientacoes">guia de leitura <ArrowRight size={15} /></a></header>
    <div className="workspace">
      <aside className="lesson-rail"><div className="rail-label">caderno de<br /><strong>evidências</strong></div><div className="rail-line">{lessons.map((lesson, index) => { const Icon = lesson.icon; return <a href={`#lesson-${index}`} key={lesson.number} className={`rail-step ${index === 0 ? "is-current" : ""}`}><span className="rail-node"><Icon size={16} /></span><span><b>{lesson.number}</b><strong>{lesson.title}</strong></span></a>; })}</div><div className="rail-foot"><LockKeyhole size={14} /> respostas individuais</div></aside>
      <main className="main-content">
        <section className="hero-section" id="orientacoes"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> atividade de ciências · 3.º bimestre</div><h1>Evolução é uma<br /><em>história de evidências.</em></h1><p>Observa as pistas, compara explicações e constrói uma leitura própria sobre como a vida se transforma e se diversifica.</p><button className="primary-button" type="button" onClick={scrollToQuestions}>começar investigação <ArrowRight size={17} /></button><div className="hero-meta"><span><b>04</b> aulas</span><span><b>12</b> pistas</span><span><b>01</b> vídeo</span></div></div><div className="hero-art"><img src={REFERENCE_IMAGE} alt="Caderno de campo com fóssil, folha e linhas de parentesco" /><div className="art-caption"><span>nota de campo · 01</span><b>toda adaptação deixa uma pista</b></div></div></section>

        <section className="student-record" id="student-record"><div className="section-intro"><span className="section-index">00 / identificação</span><h2>Antes de entrar no campo, <em>regista quem és.</em></h2><p>Esta versão pública não inclui a lista da turma. Preenche os teus dados escolares antes de responder; eles serão enviados junto com as alternativas.</p></div><div className="record-panel">{roster.length > 0 ? <div className="select-wrap"><label htmlFor="student-select">NOME DO ALUNO</label><div className="select-control"><select id="student-select" value={selectedName} onChange={(event) => setSelectedName(event.target.value)}><option value="">Seleciona o teu nome…</option>{roster.map((student) => <option value={student.nome} key={`${student.nome}-${student.numero}`}>{student.nome}</option>)}</select><ChevronDown size={18} /></div><span className="record-hint">{roster.length} nomes disponíveis · série 9.º Ano A</span></div> : <div className="select-wrap"><label htmlFor="student-name">NOME DO ALUNO</label><div className="select-control"><input id="student-name" value={manualStudent.nome} onChange={(event) => updateManualStudent("nome", event.target.value)} placeholder="Digite o teu nome completo" autoComplete="name" /></div><span className="record-hint">identificação preenchida pelo aluno · dados não ficam no repositório</span></div>}<div className="field-grid"><Field label="série" value={selectedStudent?.serie ?? manualStudent.serie} editable={roster.length === 0} onChange={(value) => updateManualStudent("serie", value)} /><Field label="número" value={selectedStudent?.numero ?? manualStudent.numero} editable={roster.length === 0} onChange={(value) => updateManualStudent("numero", value)} /><Field label="RA" value={selectedStudent?.ra ?? manualStudent.ra} editable={roster.length === 0} onChange={(value) => updateManualStudent("ra", value)} /><Field label="dígito" value={selectedStudent?.digito ?? manualStudent.digito} editable={roster.length === 0} onChange={(value) => updateManualStudent("digito", value)} /><Field label="e-mail institucional" value={selectedStudent?.email ?? manualStudent.email} wide editable={roster.length === 0} onChange={(value) => updateManualStudent("email", value)} /></div>{selectedStudent && <div className="selected-status"><span className="status-dot" /> identificação pronta <strong>{selectedStudent.situacao}</strong><span>· pronto para investigar</span></div>}</div></section>

        <section className="video-section" id="video"><div className="section-intro split-intro"><div><span className="section-index">entrada / vídeo</span><h2>Assiste como quem procura<br /><em>uma hipótese.</em></h2></div><p>O vídeo apresenta fixismo, Lamarck, Darwin e Neodarwinismo. Não copies uma definição: observa como uma explicação muda quando novas evidências entram em cena.</p></div><div className="video-frame"><video ref={videoRef} controls preload="metadata" poster={ADAPTATION_IMAGE} onTimeUpdate={(event) => { if (event.currentTarget.currentTime > event.currentTarget.duration * 0.5) setWatchedVideo(true); }}><source src={VIDEO_URL} type="video/mp4" />O teu navegador não suporta vídeo HTML5.</video><div className="video-overlay-note"><Play size={15} /> vê o recorte completo antes de responder à pista 01</div></div><div className={`video-status ${watchedVideo ? "seen" : ""}`}><span>{watchedVideo ? <Check size={15} /> : <Timer size={15} />}</span>{watchedVideo ? "já percorreste mais de metade do vídeo" : "quando avançares pelo vídeo, esta nota será atualizada"}</div></section>

        <section className="questions-section" id="questions"><div className="section-intro questions-heading"><div><span className="section-index">01—04 / investigação</span><h2>Agora, lê as pistas<br /><em>e justifica a tua escolha.</em></h2></div><div className="progress-card"><div className="progress-top"><span>progresso</span><b>{answeredCount.toString().padStart(2, "0")} / 12</b></div><div className="progress-track"><span style={{ width: `${completion}%` }} /></div><small>{completion === 100 ? "todas as pistas respondidas" : "cada resposta deixa um registo"}</small></div></div>{lessons.map((lesson, index) => <div className="lesson-block" id={`lesson-${index}`} key={lesson.number}><div className="lesson-heading"><span className="lesson-mark"><img src={MARK_IMAGE} alt="" /></span><span className="lesson-number">{lesson.number}</span><div><span>aula {lesson.number}</span><h3>{lesson.title}</h3><p>{lesson.short}</p></div></div><div className="question-stack">{questions.filter((question) => question.lesson === index).map((question) => <QuestionCard key={question.id} question={question} value={answers[question.id]} onChange={selectAnswer} submitted={submitted} isolated={isolated} setIsolated={setIsolated} />)}</div></div>)}</section>

        <section className="submit-section" id="result"><div className="submit-card"><div className="submit-mark"><ClipboardCheck size={30} /></div><div><span className="section-index">fecho de campo</span><h2>O que a tua leitura <em>conseguiu explicar?</em></h2><p>Confere se respondeste a todas as pistas. O teu registo será enviado com a identificação escolar selecionada no início.</p></div><button className="primary-button submit-button" type="button" onClick={submit} disabled={saveState.type === "saving"}>{saveState.type === "saving" ? "a registar…" : submitted ? "enviar novamente" : "enviar respostas"}<Send size={17} /></button>{saveState.message && <div className={`save-message ${saveState.type}`} aria-live="polite">{saveState.type === "saved" ? <Check size={15} /> : saveState.type === "local" ? <RotateCcw size={15} /> : <Timer size={15} />}{saveState.message}</div>}</div>{submitted && <div className="result-summary"><div><span>resultado</span><strong>{score}<small> / 12</small></strong></div><div><span>leitura</span><strong>{score >= 10 ? "investigador atento" : score >= 7 ? "hipótese em construção" : "volta às pistas"}</strong></div><div><span>estado</span><strong>{saveState.type === "saved" ? "registado" : "guardado"}</strong></div></div>}</section>
        <footer className="footer"><span>evo / campo · ciências · 9.º ano A</span><span>AE10 · EF09CI10 · EF09CI11</span><span>uma atividade para pensar com evidências</span></footer>
      </main>
    </div>
  </div>;
}
